[package]
name = "rustlearn"
version = "0.1.0"
authors = ["Ronald Coe, Jr. <rcoe@miosys.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
